### ISSUE TITLE
Link prediction code

### ISSUE THREAD

**Issue by yyou1996** [DeepGraphLearning/GMNN#4]
Hi,

It is good to see a great code for the paper. It is possible to release the link prediction code?

**Comment by yyou1996** [comment]
Sorry for the mistake. It should be link classification.

**Comment by mnqu** [comment]
Hi Yuning,

Thank you for the interest in our work!
Actually the code for link classification is the same as the one for object classification. The only difference is that F1 is used as metric instead of accuracy.
Feel free to contact me if there is still anything unclear to you.

Meng

**Comment by yyou1996** [comment]
Thank you for reply. The semi-supervised code works pretty good and not far from the reported number. 👍 However in the unsupervised code I fail to reproduce the number. I got cora: 81.42+-0.47 (82.8 in paper), citeseer: 70.14+-0.89 (71.4 in paper) with torch==0.4.1 without any modification. Is it sth wrong with my implementation?

**Comment by mnqu** [comment]
Hi Yuning,

Thank you for the detailed update!
We tested the code before the release, and it should achieve some results around 82.6 (0.5) on Cora and 71.4 (0.5) on Citeseer. Maybe there are some bugs in the released codes. I will check it and reply to you by this week.
Again, thank you for pointing it out!

Meng

**Comment by mnqu** [comment]
Hi Yuning,

I just tried running GMNN for unsupervised node representation learning with pytorch 0.4.1. The results were 82.634 (0.48) on Cora and 71.396 (0.48), which were the same as the numbers we had before.
I am not sure, but maybe we are using different versions of pytorch? because I also got quite different results under different pytorch versions. I tried fixing the problem to get stable results under different pytorch versions, but since the results on these small datasets have very high variance, I failed to do that.
Perhaps you could recheck the version of pytorch you are using, or use some larger datasets for experiment?
Please let me know if there is anything unclear to you.

Meng

**Comment by yyou1996** [comment]
Hi Meng,

Thanks for your responsible reply. Although for now we are not aimed at unsupervised task, I still appreciate your respond. I will contact you if having further unclear things.
